version: '3.8'

services:
  web:
    image: php:apache
    container_name: php-web
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www/html
    networks:
      - webnet

networks:
  webnet:
    driver: bridge
    